#!/usr/bin/env node
/**
 * Render both cuts of the /demo promo into docs/promo/.
 *
 * GitHub Pages serves docs/, so the mp4s have to live there — docs/promo/index.html picks the
 * cut by viewport and there is no build step between the repository and the published site.
 *
 *   node scripts/render-promo.mjs            # both cuts, from the repository root
 *   node scripts/render-promo.mjs vertical   # one cut
 *
 * Lives here rather than in scripts/ because this is where @remotion/* is installed;
 * scripts/render-promo.mjs at the repository root is a two-line launcher for it.
 *
 * Audio: if docs/promo/vo.mp3 exists it is mounted and muxed in. If it does not, both cuts
 * render silent and the script says so. That is deliberate — the voiceover is generated by the
 * operator (scripts/gen-vo.mjs, which reads ELEVENLABS_API_KEY from the environment), and a
 * render that blocked on a file this repository does not carry would be unrunnable for anyone
 * cloning it.
 */

import { bundle } from "@remotion/bundler";
import { stageFonts } from "./fonts.mjs";
import { renderMedia, selectComposition } from "@remotion/renderer";
import { copyFileSync, existsSync, mkdirSync, rmSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SRC = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = path.resolve(SRC, "..");
const OUT = path.join(ROOT, "docs", "promo");

const CUTS = {
  vertical: { id: "DemoPromoVertical", file: "ombs-demo-promo-9x16.mp4" },
  wide: { id: "DemoPromoWide", file: "ombs-demo-promo-16x9.mp4" },
};

const want = process.argv.slice(2).filter((a) => a in CUTS);
const cuts = want.length ? want : Object.keys(CUTS);

const vo = path.join(OUT, "vo.mp3");
const staged = path.join(SRC, "public", "vo.mp3");
const withAudio = existsSync(vo);

mkdirSync(OUT, { recursive: true });

if (withAudio) {
  // staticFile() resolves against promo-src/public, and public/vo.mp3 is gitignored — the
  // generated voiceover has exactly one home on disk (docs/promo/vo.mp3) and is staged here.
  copyFileSync(vo, staged);
  console.log("voiceover: docs/promo/vo.mp3 → mounted");
} else {
  console.log("voiceover: docs/promo/vo.mp3 not found → rendering silent");
  console.log("           run `node scripts/gen-vo.mjs` first if you want narration.");
}

console.log("\nbundling…");
stageFonts();
const serveUrl = await bundle({ entryPoint: path.join(SRC, "src", "index.ts") });

for (const key of cuts) {
  const { id, file } = CUTS[key];
  const composition = await selectComposition({
    serveUrl,
    id,
    inputProps: { withAudio },
  });
  const outputLocation = path.join(OUT, file);

  console.log(`\n${id} → docs/promo/${file}`);
  let last = -1;
  await renderMedia({
    composition,
    serveUrl,
    codec: "h264",
    outputLocation,
    inputProps: { withAudio },
    // No voiceover means NO audio track, not a silent one. docs/promo/index.html asks the file
    // whether it has audio and hides its "Tap for sound" control if it does not — an empty AAC
    // stream would answer "yes" and leave a button that plays nothing.
    muted: !withAudio,
    /**
     * One browser, frames in order.
     *
     * This composition MEASURES ITS OWN LAYOUT — the camera and the pointer are both functions
     * of `getBoundingClientRect()` on real controls — and those measurements are taken when the
     * browser mounts the page. Under the default concurrency, several browsers each mount once
     * and then render scattered frames, so any block whose height changes over the video hands
     * a later frame the wrong numbers. That shipped once: the page was 270 CSS px taller before
     * the third interest chip was tapped, and the tap at the end of the video landed 270px below
     * the link it was pressing. In the encoded file only — a still mounts fresh and is always
     * self-consistent, which is why a contact sheet of chosen frames said the shot was fine.
     *
     * The real fix is upstream: every block that changes length now reserves its tallest state
     * (`glossMin`, `verbatimMin`, `leanMin`, `calloutMin`, and the resolved card set in
     * stage/Dimensions.tsx), so the document is one height for all 600 frames. This is the belt
     * to that pair of braces, and it costs about a minute on a file rendered once.
     */
    concurrency: 1,
    /**
     * Remotion's 28s default measures a `delayRender` handle from the moment it is created, and
     * `src/fonts.ts` creates one at page load. Under the default concurrency each browser lives
     * for a short slice of the video and the handle never outlives the window; one browser
     * rendering all 600 frames does, and the render dies around frame 420 complaining about a
     * font that has long since loaded. Five minutes is still a guard, just one that fits a
     * sequential render.
     */
    timeoutInMilliseconds: 300_000,
    // Faststart so the browser can begin playing before the whole file lands — the landing
    // page autoplays this on first paint.
    x264Preset: "slow",
    onProgress: ({ progress }) => {
      const pct = Math.floor(progress * 100);
      if (pct >= last + 10) {
        last = pct;
        process.stdout.write(`  ${pct}%\n`);
      }
    },
  });
  const mb = (statSync(outputLocation).size / 1e6).toFixed(1);
  console.log(`  done · ${mb} MB`);
}

if (withAudio) rmSync(staged, { force: true });

console.log("\nRendered. docs/promo/index.html serves these directly.");
if (!withAudio) {
  console.log(
    "\n⚠  These cuts carry no audio track. The landing page detects that and hides its\n" +
      "   \"Tap for sound\" control, so nothing on it is false — but the promo ships without\n" +
      "   its voiceover. Before publishing:\n" +
      "     export ELEVENLABS_API_KEY=…  &&  node scripts/gen-vo.mjs  &&  node scripts/render-promo.mjs",
  );
}
