// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ombs-viewer/Bold.tsx": () => import("../components/mockups/ombs-viewer/Bold.tsx"),
  "./components/mockups/ombs-viewer/Minimal.tsx": () => import("../components/mockups/ombs-viewer/Minimal.tsx"),
  "./components/mockups/ombs-viewer/Scholarly.tsx": () => import("../components/mockups/ombs-viewer/Scholarly.tsx")
};
